# nohup python main.py -d unsw -m PTLAE -tbs 128 -vbs 1 -di 196 -lr 0.001 -ep 1000 -agg average -nt label_flipping -pw 0 -pr 1 -ns 0.001 -ans 1 -cs 1 -tm 1 -mc 20 -et non_iid_dir -da 1.0 > logger/unsw_log5.out 2>&1 & wait
# nohup python evaluate.py -d unsw -m PTLAE -tbs 128 -vbs 1 -di 196 -ep 1000 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/PTLAE/20/average/unsw --log_csv logs/unseen/unsw_PTLAE_ > logger/unsw_PTLAE_1000.log 2>&1 &
# nohup python evaluate.py -d unsw -m PTLAE -tbs 128 -vbs 1 -di 196 -ep 300 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/PTLAE/20/average/unsw --log_csv logs/unseen/unsw_PTLAE_ > logger/unsw_PTLAE_300.log 2>&1 
# nohup python main.py -d unsw -m SupAE -tbs 128 -vbs 1 -di 196 -lr 0.001 -ep 1000 -agg average -nt label_flipping -pw 0 -pr 1 -ns 0.001 -ans 1 -cs 1 -tm 1 -mc 20 -et non_iid_dir -da 1.0 > logger/unsw_log6.out 2>&1 
# nohup python evaluate.py -d unsw -m SupAE -tbs 128 -vbs 1 -di 196 -ep 1000 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/SupAE/20/average/unsw --log_csv logs/unseen/unsw_SupAE_ > logger/unsw_SupAE_200.log 2>&1 
# nohup python main.py -d unsw -m FedHome -tbs 128 -vbs 1 -di 196 -lr 0.001 -ep 1000 -agg average -nt label_flipping -pw 0 -pr 1 -ns 0.001 -ans 1 -cs 1 -tm 0 -mc 20 -et non_iid_dir -da 1.0 > logger/unsw_log8.out 2>&1 
# nohup python evaluate.py -d unsw -m FedHome -tbs 128 -vbs 1 -di 196 -ep 1000 -tm 0 -mc 20 -et non_iid_dir --model_dir saved_models/FedHome/20/average/unsw --log_csv logs/unsw_FedHome_ > logger/unsw_FedHome_20.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2200 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2200.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2190 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2190.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2180 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2180.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2170 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2170.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2160 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2160.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2150 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2150.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2140 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2140.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2130 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2130.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2120 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2120.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2110 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2110.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2100 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2100.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2090 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2090.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2080 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2080.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2070 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2070.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2060 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2060.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2050 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2050.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2040 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2040.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2030 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2030.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2020 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2020.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2010 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2010.log 2>&1 
nohup python evaluate.py -d unsw -m DualLossAE -tbs 128 -vbs 1 -di 196 -ep 2000 -tm 1 -mc 20 -et non_iid_dir --model_dir saved_models/DualLossAE/20/average/unsw --log_csv logs/unsw_DualLossAE_ > logger/unsw_DualLossAE_2000.log 2>&1
